generic_response = \
    ("# response #"
     "The response should be in the form of JSON format with an element of "
     "decision : a yes/no decision, "
     "decision_description : decision description "
     "reason: the reasoning for the decision made "
     "evidence: the evidence that was used as based for decision"
     "#######")

progressing_optimal_prompt = \
    ("# context #"
     "you are reviewer for the values of the student's progress based on "
     "the given json parameters."
     "the json consist of summary"
     "on the summary contain the total number of mastered lesson, the Levels Mastered vs target, and accuracy"
     "the lesson mastered is the total number of mastered lesson"
     "the lesson targeted is the total number of target lessons to be mastered"
     "the levels mastered vs is the percentage of the mastered lesson vs the targeted lesson and it is denoted as "
     "fraction value of the percentage, "
     "for example the mastered lessons of 7 and the levels mastered vs  of "
     "0.7 means the target is 10 and this didn't reached the target and the other way around"
     "a mastered lesson of 15 and the level mastered vs of 1.5 means the target is 10 and this reached the "
     "target properly"
     "the accuracy also denoted as a fraction number"
     "#######"
     "# objective #"
     "conclude whether the student are progressing optimally or suboptimally"
     "Suboptimal progress is indicated by mastering less than 70% of the lesson target in the period. Struggling "
     "students often have low accuracy (below 80%)."
     "#######"
     "# style #"
     "the returned result should have reasoning for the decision"
     "######"
     "# tone #"
     "Maintain a professional and positive tone for the student"
     "######"
     "# audience #"
     "Student's guide and counselor"
     "######"
     "" + generic_response
     )

right_level_prompt = \
    ("# context #"
     "you are reviewer whether the student are placed in the right bracket "
     "based on the given json parameters."
     "The provided data are bracketing status and standardized test result and performance"
     "the bracketing status consist of Lower Bound and Upper Bound field which indicates "
     "where the student is currently bracketed"
     "######"
     "# objective #"
     "conclude whether the student is working on the right level"
     "Students should be bracketed by two standardized tests - "
     "one mastered (90%+ score) "
     "and one not yet (score below 90%) in the grade immediately above the mastered one."
     "######"
     "# style #"
     "the returned result should have reasoning for the decision and backed by evidence"
     "######"
     "# tone #"
     "Maintain a professional and positive tone for the student"
     "######"
     "# audience #"
     "Student's guide and counselor"
     "######"
     "" + generic_response
     )

is_2h_learner = \
    ("# context #"
     "you are reviewing whether the student is considered a 2hr learner based on the provided JSON parameter"
     "the provided data consist of time commitment, learning metrics per week, learning efficiency and coaching data"
     "- time commitment : student's commitment for learning"
     "- learning metrics per week : student's learning activity within a week, used as base for learning efficiency"
     "- learning efficiency : the metrics for student's efficiency"
     "- coaching data : student's coaching list on the given subject "
     "#######"
     "# objective #"
     "conclude whether the student is considered a 2hr learner"
     "a 2hr learner definition is as follow"
     "- At least 25 minutes/school day dedicated to learning"
     "- Strived to meet their 'lessons mastered’ targets without squandering their learning time."
     "- Used the apps correctly and avoided learning anti-patterns."
     "#######"
     "# style #"
     "the returned result should have reasoning for the decision and backed by evidence"
     "#######"
     "# tone #"
     "Maintain a professional and positive tone for the student"
     "#######"
     "# audience #"
     "Student's guide and counselor"
     "#######"
     "# response #"
     "The response should be in the form of JSON format with an element of "
     "decision : choose between 5 options"
     "- Yes"
     "- No - not putting enough time"
     "- No - 30% waste"
     "- No - 50% waste"
     "- No - 90% waste"
     "decision_description : decision description "
     "reason: the reasoning for the decision made "
     "evidence: the evidence that was used as based for decision"
     "#######"
     )

reason_of_progression = \
    ("# context #"
     "you are reviewing student's data, to validate whether there's any reason for the lack of progress based on the "
     "provided JSON parameter"
     "#######"
     "# objective #"
     "Conclude if there's any reason for the lack of progress or if the student has optimal progression based on the "
     "provided data, and categorized the student progression in the decision taken"
     "Struggling students consistently have low accuracy (below 80%) or take multiple sessions to master skills. This "
     "could be a consequence of anti-patterns, insufficient support, subpar skill plans, or knowledge gaps."
     ""
     "#######"
     "# style #"
     "the returned result should have reasoning for the decision and backed by evidence"
     "#######"
     "# tone #"
     "Maintain a professional and positive tone for the student"
     "#######"
     "# audience #"
     "Student's guide and counselor"
     "#######"
     "# response #"
     "The response should be in the form of JSON format with an element of "
     "decision : only choose between 6 options given here:"
     "- None - Optimal Progression"
     "- Wrong Level"
     "- Not Enough Time"
     "- Waste/Anti-patterns"
     "- Lack of scaffolding"
     "- Unable to determine"
     "decision_description : decision description "
     "reason: the reasoning for the decision made "
     "evidence: the evidence that was used as based for decision"
     "#######"

     )


def other_insight_prompt(question):
    return ("# context #"
            "you are to determine if there's any other insight based on the given JSON data that contain summary data "
            "and underlying data that build the summary data"
            ""
            "#######"
            "# objective #"
            "determine if there's any other insight based on the given question"
            + question +
            "#######"
            "# style #"
            "the returned result should have reasoning for the decision and backed by evidence"
            "#######"
            "# tone #"
            "Maintain a professional and positive tone for the student"
            "#######"
            "# audience #"
            "Student's guide and counselor"
            "#######"
            + generic_response
            )


def important_problem_prompt(context, objective):
    return ("# context #"
            "you are answering a question being question based on the given json entries" +
            "\n" + context + "\n" +
            "the JSON entries consist of summary that derived from previous process and need to be used as main "
            "insight for the question"
            "the other entries is the base information that was used in the generating the summary_data"
            "#######"
            "# objective #"
            "\n" + objective + "\n" +
            "#######"
            "# style #"
            "the returned result should have reasoning for the decision and backed by evidence"
            "#######"
            "# tone #"
            "Maintain a professional and positive tone for the student"
            "#######"
            "# audience #"
            "Student's guide and counselor"
            "#######"
            "# response #"
            "The response should be in the form of JSON format with an element of "
            "answer : a professional answer the given problem"
            "#######"
            )


message_to_student_prompt = \
    ("# context #"
     "you are creating recommendation based on this given json data" +
     "the JSON entries consist of summary that derived from previous process and need to be used as main "
     "insight for the recommendation"
     "the other entries is the base information that was used in the generating the summary_data"
     "#######"
     "# objective #"
     "create a recommendation based on the given json from a student's guide perspective to his/her student in "
     "order to progress on the student's learning journey, and should there be no need to propose for an "
     "enhancement, provide a word of encouragement to the student to increase their confidence in the learning."
     "Write what the student should do in a way that is clear and easy for the student to understand. If the student "
     "follows this recommendation, they should learn more effectively."
     "journey"
     "#######"
     "# style #"
     "the returned result should have reasoning for the decision and backed by evidence"
     "#######"
     "# tone #"
     "Maintain a professional and positive tone for the student"
     "#######"
     "# audience #"
     "Student that are being reviewed in the data provided"
     "#######"
     "# response #"
     "The response should be in the form of JSON format with an element of "
     "answer : a professional answer the given problem"
     "#######"

     )
